### ISSUE TITLE
Is it possible to use scaffold assembly as input for SALSA?

### ISSUE THREAD

**Issue by hungweichen0327** [marbl/SALSA#100]
Hello,

Thank you for this great software SALSA that has fast running time and useful for scaffolding.
I read the README file and know SALSA using contig-level assembly. I am curious that is it possible to use scaffold-level draft assembly as input for SALSA? Some assembler (like Flye) can order contigs into scaffolds based on the repeat graph structure.

**Comment by dtg-jayghurye** [comment]
Yes, you can use those scaffolds as input to SALSA. If there are any misjoins in those scaffolds, SALSA will attempt to correct those prior to scaffolding.

**Comment by ghuryejay** [comment]
Yes, you can use those scaffolds as input to SALSA. If there are any misjoins in those scaffolds, SALSA will attempt to correct those prior to scaffolding.

**Comment by hungweichen0327** [comment]
Thank you for the reply. I will also try to use scaffold-level draft assembly as input.
