### ISSUE TITLE
Do I need to perform a polishing step after using SALSA?

### ISSUE THREAD

**Issue by uceleste** [marbl/SALSA#102]
Hi All,

I have successfully used SALSA on my assembly (I used the -m option). Before using SALSA, my assembly has already undergone proper polishing processes by using Arrow and Pilon.
My question is simple: do I need to perform a polishing step after using SALSA? Are there other recommended software to be used after SALSA or can I move directly to the annotation of the assembly?

Thanks

**Comment by skoren** [comment]
No you do not need to polish after SALSA since it will not change the sequence of your contigs. However, polishing with a tool like Arrow will potentially fill gaps so you may want to run it to do that rather than polishing the bases.

**Comment by uceleste** [comment]
Thanks for your help!
