### ISSUE TITLE
-u no longer available

### ISSUE THREAD

**Issue by malonge** [marbl/SALSA#106]
Hi there,

It looks like the `-u` option has been removed since v2.1. Since I assume it is no longer supported, what is your advice for scaffolding Canu unitigs?

I was originally thinking I would set the following parameters

```
-a asm.unitigs.fasta
-g asm.unitigs.gfa
-u asm.unitigs.bed
```

I suppose I could just use the contigs instead, but then I think Salsa can't utilize an assembly graph, since HiCanu doesn't provide a graph for contigs. Is that right?

Thanks in advance,
Mike

**Comment by malonge** [comment]
Or maybe I should just exclude `-u` and use `stitch.py` to bring in the contig information after the fact?

**Comment by ghuryejay** [comment]
You are right. You should use `stitch.py` to bring unitig to contig information after scaffolding.

**Comment by malonge** [comment]
Thanks!
