### ISSUE TITLE
Error: Operation not supported

### ISSUE THREAD

**Issue by brettmorg** [marbl/SALSA#108]
Hello, 
When I attempt to run SALSA with:

`/usr/bin/python2.7 /home/xylotrupes//Desktop/software/SALSA-master/run_pipeline.py -a maya_1.fasta -l maya_1.fasta.fai -b maya_sort.bed -e GATC`

I'm met with the following: 

```
Traceback (most recent call last):
  File "/home/xylotrupes/Desktop/software/SALSA-master/run_pipeline.py", line 360, in <module>
    main()
  File "/home/xylotrupes/Desktop/software/SALSA-master/run_pipeline.py", line 90, in main
    os.symlink(os.path.abspath(args.bed),args.output+'/alignment_iteration_1.bed')
OSError: [Errno 95] Operation not supported
```
Seems like python is not recognizing something, what can I do to resolve it? My python version is 2.7.17 if that helps.
Thanks very much!

**Comment by skoren** [comment]
This doesn't look like a python or salsa issue but your file system not supporting symlinks. This is the first symlink Salsa tries to make while running and it is failing. Are you on a VM that doesn't allow symlinks? Can you manually try making a symlink and see if it works? If your system doesn't support symlinks, you'd have to edit Salsa's code to change all symlinks to copy operations.

**Comment by brettmorg** [comment]
Ah ok, the assembly files are on a NAS, and when I move them to the local drive there is no problem. Thank you!
