### ISSUE TITLE
Salas can't find <boost/config.hpp>

### ISSUE THREAD

**Issue by Hannah1746** [marbl/SALSA#112]
Hello,

I am trying to install Salsa on to my Ubuntu computer. I have installed boost and nextworkx 1.1. When I try to make Salsa I get:
g++ -O3 -Wall -Wextra -std=c++11 -o correct_links correct_links.cpp
correct_links.cpp:12:10: fatal error: boost/config.hpp: No such file or directory
 #include <boost/config.hpp>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:15: correct_links] Error 1
I have boost installed and can see the boost/config directory on my computer and even exported that directory to my path but salsa still can't seem to find it.

Please let me know what I am doing wrong

**Comment by skoren** [comment]
You need to tell GCC where to find boost, even though it's installed it's not in your compilation path. You can add the include file by adding -I<path to boost folder> to the g++ command line in the Makefile or add the path to the CPATH environment variable. See the GCC documentation for more info: https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html. You may also need to add the library location for boost to the LIBRARY_PATH environment variable.
