### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Hannah1746** [marbl/SALSA#114]
Hey when I try to run salsa:
python ~/SALSA-master/run_pipeline.py -a BW_racon3.pilon2_shasta.fasta -l BW_racon3.pilon2_shasta.fasta.fai -b BW_shasta.bed -e CATG -o scaffolds_shasta -m yes -g contigs_graph.gfa

I get this error:
File "/home/SALSA-master/layout_unitigs.py", line 827, in update_bed
    first = prev_attrs[3].split('/')[1]
IndexError: list index out of range

Can you help me understand why I am getting this error?

**Comment by ttian627** [comment]
I got the same error, you can change the sam to bam and then bam to bed formate.

**Comment by Hannah1746** [comment]
But I already did that through this code


#Map raw read to reference
bwa index BW_PoreC_all.fastq
bwa mem -t 10 "BW" BW_racon2_pilon2_miniasm.fasta BW_PoreC_all.fastq > BW_PoreC_shasta_mapped_reads.sam; samtools view -b -@ 1 BW_PoreC_shasta_mapped_reads.sam | samtools sort -@ 1 -o BW_shasta.sorted.bam ; samtools index BW_shasta.sorted.bam
#Turn bam into bed
bamToBed -i BW_shasta.sorted.bam > BW_shasta.bed
#Sort the bam file
sort -k 4 BW_shasta.bed > tmp && mv tmp BW_shasta.bed

**Comment by ttian627** [comment]
OK， I change sam to bed and got the same errors.
















At 2020-11-09 05:52:47, "Hannah1746" <notifications@github.com> wrote:

But I already did that through this code

#Map raw read to reference
bwa index BW_PoreC_all.fastq
bwa mem -t 10 "BW" BW_racon2_pilon2_miniasm.fasta BW_PoreC_all.fastq > BW_PoreC_shasta_mapped_reads.sam; samtools view -b -@ 1 BW_PoreC_shasta_mapped_reads.sam | samtools sort -@ 1 -o BW_shasta.sorted.bam ; samtools index BW_shasta.sorted.bam
#Turn bam into bed
bamToBed -i BW_shasta.sorted.bam > BW_shasta.bed
#Sort the bam file
sort -k 4 BW_shasta.bed > tmp && mv tmp BW_shasta.bed

**Comment by Hannah1746** [comment]
Did you ever figure out how to get around this error?

**Comment by ttian627** [comment]
I tried this pipline (https://github.com/ArimaGenomics/mapping_pipeline), that the SALSA paper recommend.
















At 2020-11-10 02:13:05, "Hannah1746" <notifications@github.com> wrote:

Did you ever figure out how to get around this error?
