### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by alanorth** [marbl/SALSA#117]
I'm installing SALSA for use on [our cluster](https://hpc.ilri.cgiar.org/) and I see there have been fourteen commits to master since the v2.2 tag in 2018. Because there's no recent tag I guess I'll have to install it with version `git-974589f3` or something. Can you please tag a new release to make this less ugly? Thanks. :)

**Comment by skoren** [comment]
v2.3 has been tagged by @ghuryejay
