### ISSUE TITLE
sort -k4 

### ISSUE THREAD

**Issue by harmeet1990** [marbl/SALSA#120]
I have sorted my bedfile using sort -k4 bam.file. But it doesn't behave as expected. Please see bold text below. My question does runSALSA.py takes the read names into account while trying to establish Hi-C links or one single read which is out of order would lead to the offsetting of the entire file?

utg18515	4425545	4425646	ERR4277421.1000000/1	51	-
utg18515	4425310	4425411	ERR4277421.1000000/2	51	+
utg3607	8222302	8222403	ERR4277421.1000006/1	25	+
utg3607	8222374	8222475	ERR4277421.1000006/2	10	-
utg27429	6837435	6837536	ERR4277421.1000007/1	60	+
utg27429	6837816	6837917	ERR4277421.1000007/2	60	-
utg4900	1942713	1942814	ERR4277421.1000009/1	60	-
utg37812	1735861	1735951	ERR4277421.1000009/2	54	-
utg20223	2805617	2805667	ERR4277421.100001/1	15	+
utg39481	5444272	5444373	ERR4277421.100001/2	60	-
utg9137	5531602	5531703	ERR4277421.1000013/1	60	+
utg9137	5531729	5531830	ERR4277421.1000013/2	60	-
**utg1528	120310	120411	ERR4277421.10000/1	46	-**
utg50112	912054	912155	ERR4277421.1000015/1	60	+
utg50112	912091	912192	ERR4277421.1000015/2	60	-
utg7587	10888026	10888079	ERR4277421.1000018/1	12	+
utg51270	671972	672073	ERR4277421.1000018/2	60	-
utg4118	11836484	11836585	ERR4277421.1000021/1	60	-
utg4118	11836330	11836431	ERR4277421.1000021/2	60	+
utg2929	15215735	15215836	ERR4277421.1000023/1	60	-
utg7021	2812319	2812420	ERR4277421.1000023/2	60	+
**utg29785	475055	475156	ERR4277421.10000/2	53	-**
utg22791	981406	981507	ERR4277421.1000028/1	60	+
utg22791	981437	981538	ERR4277421.1000028/2	56	-
utg66868	585748	585849	ERR4277421.1000029/1	60	+
utg66868	585863	585964	ERR4277421.1000029/2	60	-

**Comment by ghuryejay** [comment]
A single read that is out of order should not matter as the code only looks for the adjacent lines in the file. 

Although, it's interesting why the sort -k4 behaves this way.
