### ISSUE TITLE
ln: failed to create symbolic link 'scaffolds/assembly.cleaned.fasta': File exists mv: cannot stat 'scaffolds//asm.cleaned.fasta': No such file or directory

### ISSUE THREAD

**Issue by wjj666** [marbl/SALSA#122]
Hello, when I run the command: python run_pipeline.py -a *.fa -l *.fa.fai -b *.bed -e GATC -o scaffolds -m yes

there are some errors:

ln: failed to create symbolic link 'scaffolds/assembly.cleaned.fasta': File exists
mv: cannot stat 'scaffolds//asm.cleaned.fasta': No such file or directory

Could please tell how to solve these errors? Thank you very much.

**Comment by ens-LCampbell** [comment]
I am having the exact same issue ! Would love if someone could help out and clear this up

**Comment by jksull** [comment]
Hi there, thought I could possibly try help as i've also recently encountered this.  First things first, did you compile salsa2 using make (requires boost and networkx installed)? Depending on where you look, this `make` step may or may not be explicitly mentioned for installation instructions - it was something I missed to begin with.

Secondly, are you working with a fasta file that comes from Bionano Solve pipeline, and subsequent N-trimming? There seems to be a problem with some special characters that bionano solve process puts into the fasta headers, which can mess with salsa2 proficiency.

**Comment by ens-LCampbell** [comment]
I had recent success with Running SALSA. I had initially installed SALSA with compiling via 'make' following a fresh git clone. But I had issues with python libraries, in that our cluster had python2.7 installed but without networkx. I had to install my own version of python2.7 (v2.7.15) with conda, as v 2.7.12 seemingly was causing syntax exception issues as well as missing networkx. Following installing v2.7.15, ensuring networkx modules were in PYTHONPATH and having compiled fresh with make following downloading... I was able to get SALSA to run to completion.

**Comment by plnspineda** [comment]
> Hi there, thought I could possibly try help as i've also recently encountered this. First things first, did you compile salsa2 using make (requires boost and networkx installed)? Depending on where you look, this `make` step may or may not be explicitly mentioned for installation instructions - it was something I missed to begin with.
> 
> Secondly, are you working with a fasta file that comes from Bionano Solve pipeline, and subsequent N-trimming? There seems to be a problem with some special characters that bionano solve process puts into the fasta headers, which can mess with salsa2 proficiency.

Hi, seems like I have the same problem with special characters. I have "_" in some contig names, some have "hap_", and I am getting error in reading the fasta file. With uniform fasta names, it works just fine. Could it be the problem?
