### ISSUE TITLE
Dealing with haplotigs in raw assembly graphs

### ISSUE THREAD

**Issue by Adamtaranto** [marbl/SALSA#124]
I'm trying to work out how SALSA will deal with large bubbles in unphased diploid genome graphs. The SALSA paper notes that heterozygous genome assemblies should be de-duplicated before scaffolding i.e with purge_dups to minimise misassemblies. 

Is it necessary to remove duplicate contigs when scaffolding from a unitig graph rather than a contig fasta? or will the gfa information prevent false concatenation of duplicated/haplotig sequences?

**Comment by skoren** [comment]
You would need to de-duplicate the unitigs as well. There's no phasing capability in salsa and so no guarantee it will keep the haplotypes correct or avoid merging bubbles (since it doesn't annotate the bubbles in any way).
