### ISSUE TITLE
break_contigs_start: not found

### ISSUE THREAD

**Issue by Lattesnow** [marbl/SALSA#132]
Hey,
I followed Arima genomics pipeline to generate my bed files and use python run_pipeline.py -a contigs.fasta -l contigs.fasta.fai -b alignment.bed -e {GATC,GANTC} -o scaffolds -m yes to run but got a bunch of errors:
/bin/sh: 1: /mnt/e/Process/SALSA/break_contigs_start: not found
Error, your fasta records contain a ':' (HLA-DQB1*06:03:01). SALSA requires fasta to not contain this character, please update your fasta and re-try
The fasta reference is hg38

TZ

**Comment by skoren** [comment]
The missing file looks like SALSA wasn't compiled. Did you run `make` in the SALSA folder after getting it from GitHub? Did that give any error messages?

The second message is warning you that SALSA does not support fasta headers with ":" in the name, you'll have to rename your fasta records.

**Comment by Lattesnow** [comment]
Hey Skoren,
This is what I got after run make in the Salsa folder
g++ -O3 -Wall -Wextra -std=c++11 -o break_contigs break_contigs.cpp
make: execvp: g++: Permission denied
make: *** [Makefile:9: break_contigs] Error 127
I installed the boost and networkx as described in the Readme file. 

I saw #20 is related to the ":". Will correct this.
Thanks

**Comment by skoren** [comment]
That error looks like you don't have a C++ compiler (g++) installed on your system. Try installing one and then confirm `which g++` returns a path to an executable and run make again.
