### ISSUE TITLE
Two HiC experiments: recommend combine data or run SALSA sequentially?

### ISSUE THREAD

**Issue by ckeeling** [marbl/SALSA#133]
Hello,

I have HiC (Chicago) and HiC data, and a gfa file for the draft assembly to scaffold. I am trying both ways, but conceptually, would there be any problem combining the reads from both HiC datasets into one for mapping for SALSA, so that SALSA is informed by the gfa file with the longer-range HiC data, and not just the Chicago HiC data if run sequentially?

Thanks,
Chris

**Comment by skoren** [comment]
I would expect sequential runs would work better. The issue with combining these libraries is they will have very different length distributions and I worry the selection of best edges might get skewed by this. If you finished the runs, feel free to post which turned out better.

**Comment by ckeeling** [comment]
I found little difference between doing it sequential or in combination in my case. Thus, using the combination allows one to work downstream (e.g. JBAT) on just one assembly rather than step-wise.
