### ISSUE TITLE
sorting bed file

### ISSUE THREAD

**Issue by kishor2019** [marbl/SALSA#134]
Hi,
I am having issue with sorting bed file. The commands and errors are following:
bedtools bamtobed -i sardina_aln_sorted.bam > sardina_aln.bed
sort -k 4 sardina_aln.bed > tmp && mv tmp sardina _aln.bed

sort: write failed: /tmp/sortZqagw9: No space left on device

But i have checked that i have enough space in my disk. Can you please help me to solve this problem?

**Comment by skoren** [comment]
The out of space message is from sort due to the temporary space being full (`/tmp`). You can specify a different temp location for sort using the -T option (`-T $PWD` as salsa does when it runs sort internally).

**Comment by kishor2019** [comment]
Its has worked now. Thanks.
