### ISSUE TITLE
Proximo Hi-C (Phase Genomics)

### ISSUE THREAD

**Issue by carolhsb** [marbl/SALSA#135]
Hello,

I have Hi-C data that was constructed with Proximo Hi-C Kit (Phase Genomics). Can I use this data in Salsa?

Thanks in advance,

Carol

**Comment by amvarani** [comment]
You can use Phase Genomics HiC data normally. I have good results using Arima Genomics mapping pipeline or using bwa and samblast only. For example: 
bwa mem -5SP [assembly.fasta] [fwd_hic.fastq] [rev_hic.fastq] | samblaster | samtools view -S -h -b -F 2316 > [aligned.bam]

**Comment by carolhsb** [comment]
Hi,

thanks!
I've used with Arima Genomics mapping pipeline too, and it worked.

**Comment by shaferab** [comment]
hi @carolhsb or @amvarani - would you mind sharing info on genome size and no mapped HiC reads - I'm seeing zero improvement in my assembly and trying to troubleshoot.
