### ISSUE TITLE
KeyError: 

### ISSUE THREAD

**Issue by kalbflei** [marbl/SALSA#140]
Hello,

    I am getting an error in layout_unitigs.py. 

[tska223@dtn HiC]$ python /opt/SALSA/layout_unitigs.py -x abc -l scaffold/contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d scaffold
Loading Hi-C links 
Traceback (most recent call last):
  File "/opt/SALSA/layout_unitigs.py", line 929, in <module>
    generate_scaffold_graph()
  File "/opt/SALSA/layout_unitigs.py", line 392, in generate_scaffold_graph
    if contig_length[c1] <= int(args.cutoff) or contig_length[c2] <= int(args.cutoff):
KeyError: 'tig00004415_subseq_1'

When I look at tig00004415_subseq_1, I see a wonky name (This is data created by Bionano scaffolding pipeline) tig00004415_subseq_1:35771_obj. Not sure what's wrong, but if you could point me in the right direction, I would be grateful.

--Ted

**Comment by skoren** [comment]
SALSA doesn't support fasta config names with ":" in the name, which bionano produces. Rename these to replace `:` with something else like `_` and re-start the pipeline from scratch and it should run.

**Comment by kalbflei** [comment]
Thank you!
