### ISSUE TITLE
ImportError: No module named networkx

### ISSUE THREAD

**Issue by khush876** [marbl/SALSA#142]
Hi, 

I tried to scaffold a plant genome and tried below mentioned command.

python run_pipeline.py -a contigs.fasta -l contigs.fasta.fai -b alignment.bed -e {Your Enzyme} -o scaffolds

But I am receiving an error message: ImportError: No module named networkx

Am I running it wrong?

Thank you

**Comment by skoren** [comment]
NetworkX is a required python module: "To run the code, you will need Python 2.7, BOOST libraries and Networkx(version lower than 1.2)." You'll need to install networkx on your system so it's available to python and it should run.
