### ISSUE TITLE
Restriction sites where the cut-site is in the middle.

### ISSUE THREAD

**Issue by DustinSokolowski** [marbl/SALSA#144]
Hey!

Thank you for the great tool. The HI-C protocol I used has a handful of RE's. Of those, there are a few who have their cut-site in the middle (e.g., G^AATC). Does this need to be specified in the script or does anything need to be different compared to the GATC example which is (if I'm not mistaken) ^GATC ? 

Thanks so much!
Dustin

**Comment by skoren** [comment]
You can just specify the full string, no need to indicate where the exact cut site is.

**Comment by DustinSokolowski** [comment]
Awesome, thank you!
