### ISSUE TITLE
minimap aligner

### ISSUE THREAD

**Issue by sammywinchester19** [marbl/SALSA#147]
Can minimap2 aligner be used instead of bwa-mem and bowtie2?

Suleman.

**Comment by skoren** [comment]
SALSA doesn't care about the aligner so you can use whatever you want to generate the input bam/pairs file. However, the recommended mapping pipeline has not been tested/validated with minimap2 so you may get sub-optimal results. As far as I know, minimap2 isn't optimized for short read mapping like those from HiC runs.
