### ISSUE TITLE
No Change in Assembly stats after HiC salsa

### ISSUE THREAD

**Issue by shaferab** [marbl/SALSA#158]
HI - I have 45x HiFi data and 370M HiC reads. I've followed the the VGP pipeline - so a purged Canu assembly - my final bed file has 27M entries. I run salsa 2.2 (command below) and there's no change in the assembly. Anything obvious I'm missing?

#!/bin/bash
#SBATCH --time=2-0
#SBATCH --account=rrg-shaferab
#SBATCH --mem=32G
#SBATCH --cpus-per-task=4
source ../conda/conda/etc/profile.d/conda.sh
conda activate salsa_env
module load python/2.7
enz=`cat re_bases.txt`
python ../SALSA-2.2/run_pipeline.py -a purged.fa -l purged.fa.fai -e $enz -b dp_sorted_HiC_filtered.bed -o scaffolds_salsa -m yes -p yes
ln -s scaffolds_salsa/scaffolds_FINAL.fasta ${fasta/_s2/_s3}

**Comment by shaferab** [comment]
Essentially this is the same issue as #107

**Comment by shaferab** [comment]
Resolved. VGP sort different than salsa manual - required:
sort -k 4 alignment.bed > tmp && mv tmp alignment.bed

**Comment by gubrins** [comment]
heys @shaferab I am having the same issue. What do you mean the the sorting is different? What are you sorting in your last comment? What is this alignment file and you do it before or after the scaffolding?
Thanks in advance!
