### ISSUE TITLE
possible to phase haplotypes?

### ISSUE THREAD

**Issue by zhaotao1987** [marbl/SALSA#159]
It looks very exciting of SALSA2 using Hi-C and GFA. Just wondered if it's possible to apply the pipeline to my triploid genome (AAB type). I'm using all halplotigs as the input genome fasta. Would it work to group and phase haplotypes? Thanks a lot!

**Comment by skoren** [comment]
No, SALSA doesn't have any functionality to filter contigs by haplotype. It is meant to scaffold a single haplotype at a time and if there multiple haplotypes it'll likely just scaffold all the alt contigs together next to each other. You'd have to bin the contigs somehow (or select a representative haplotype) and scaffold that.
