### ISSUE TITLE
Does SALSA use multiple threads/cores?

### ISSUE THREAD

**Issue by romseg** [marbl/SALSA#160]
Hi,

I am wondering whether SALSA use multiple threads/cores and how to set this option? Or perhaps it's not needed? Thank you.

Rom

**Comment by skoren** [comment]
SALSA doesn't, it's relatively quick to run so not worth parallelizing. The read mapping does use multiple cores and that is described on the arima mapping GitHub and in the SALSA readme (under "Mapping Reads")
