### ISSUE TITLE
YAHS

### ISSUE THREAD

**Issue by larryns** [marbl/SALSA#162]
Hi,

This is more of a general guidance question, but does anyone know how SALSA2 and YAHS compare? I have heard some people recommending YAHS instead of SALSA2, and I was wondering if anyone had experience or thoughts on how the tools compare.

Thanks for your insight.

Best regards,
Larry.

**Comment by skoren** [comment]
We're not actively developing SALSA anymore so it's possible YAHS has updated features/improvements since it was developed more recently.

**Comment by larryns** [comment]
Thanks for the info. May I ask if there's a planned replacement for SALSA? We have a pipeline in place with HiCanu and SALSA, so we're curious if we'll need to modify it.  Thanks for your help.
