### ISSUE TITLE
no scaffold assembly, the assembly stats is no change

### ISSUE THREAD

**Issue by guo-cheng** [marbl/SALSA#164]
Hi developers,
Below is my script running SALSA2，but the output shows the assembly stats is no change.

`~/miniconda3/envs/py2.7/bin/python /public1/home/ligch/software/SALSA/run_pipeline.py -a /public1/home/ligch/Harm_Hass_genome/Harm/03_HiC_assembly/reference/Harm.asm.dip.hap1.p_ctg.fa -l /public1/home/ligch/Harm_Hass_genome/Harm/03_HiC_assembly/reference/Harm.asm.dip.hap1.p_ctg.fa.fai -b Harm.hap1.alignment.sorted_k4.bed -e GATC -o Harm.hap1.scaffold -m yes -p yes -g /public1/home/ligch/Harm_Hass_genome/Harm/02_assembly/Harm_test1.asm.dip.hap1.p_ctg.gfa`

Best！
Guo-Cheng Li

**The Log file:**

bedfile loaded
Starting Iteration 1
bedfile started
bedfile loaded
Done loading GFA file
Number of Nodes = 0
Number of Edges = 0
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 122 edges = 85
Hi-C implied edges = 0
Starting Iteration 2
bedfile started
bedfile loaded
Starting Iteration 2
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 94 edges = 62
Hi-C implied edges = 0
Starting Iteration 3
bedfile started
bedfile loaded
Starting Iteration 3
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 64 edges = 38
Hi-C implied edges = 0
python2 /public1/home/ligch/software/SALSA/RE_sites.py -a Harm.hap1.scaffold/assembly.cleaned.fasta -e GATC > Harm.hap1.scaffold/re_counts_iteration_1
python2 /public1/home/ligch/software/SALSA/make_links.py -b Harm.hap1.scaffold/alignment_iteration_1.bed -d Harm.hap1.scaffold -i 1 -x abc
python2 /public1/home/ligch/software/SALSA/fast_scaled_scores.py -d Harm.hap1.scaffold -i 1
sort -k 5 -gr Harm.hap1.scaffold/contig_links_scaled_iteration_1 > Harm.hap1.scaffold/contig_links_scaled_sorted_iteration_1
python2 /public1/home/ligch/software/SALSA/layout_unitigs.py -x /public1/home/ligch/Harm_Hass_genome/Harm/02_assembly/Harm_test1.asm.dip.hap1.p_ctg.gfa -l Harm.hap1.scaffold/contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d Harm.hap1.scaffold
/public1/home/ligch/software/SALSA/break_contigs -a Harm.hap1.scaffold/alignment_iteration_2.bed -b Harm.hap1.scaffold/breakpoints_iteration_2.txt -l Harm.hap1.scaffold/scaffold_length_iteration_2 -i 2 -s 100   > Harm.hap1.scaffold/misasm_iteration_2.report
python2 /public1/home/ligch/software/SALSA/refactor_breaks.py -d Harm.hap1.scaffold -i 2
python2 /public1/home/ligch/software/SALSA/make_links.py -b Harm.hap1.scaffold/alignment_iteration_2.bed -d Harm.hap1.scaffold -i 2
python2 /public1/home/ligch/software/SALSA/layout_unitigs.py -x abc -l Harm.hap1.scaffold/contig_links_scaled_sorted_iteration_2 -c 1000 -i 2 -d Harm.hap1.scaffold
/public1/home/ligch/software/SALSA/break_contigs -a Harm.hap1.scaffold/alignment_iteration_3.bed -b Harm.hap1.scaffold/breakpoints_iteration_3.txt -l Harm.hap1.scaffold/scaffold_length_iteration_3 -i 3 -s 100  > Harm.hap1.scaffold/misasm_iteration_3.report
python2 /public1/home/ligch/software/SALSA/refactor_breaks.py -d Harm.hap1.scaffold -i 3 > Harm.hap1.scaffold/misasm_3.log
python2 /public1/home/ligch/software/SALSA/make_links.py -b Harm.hap1.scaffold/alignment_iteration_3.bed -d Harm.hap1.scaffold -i 3
python2 /public1/home/ligch/software/SALSA/layout_unitigs.py -x abc -l Harm.hap1.scaffold/contig_links_scaled_sorted_iteration_3 -c 1000 -i 3 -d Harm.hap1.scaffold
/public1/home/ligch/software/SALSA/break_contigs -a Harm.hap1.scaffold/alignment_iteration_4.bed -b Harm.hap1.scaffold/breakpoints_iteration_4.txt -l Harm.hap1.scaffold/scaffold_length_iteration_4 -i 4 -s 100  > Harm.hap1.scaffold/misasm_iteration_4.report
python2 /public1/home/ligch/software/SALSA/refactor_breaks.py -d Harm.hap1.scaffold -i 4 > Harm.hap1.scaffold/misasm_4.log

**Comment by skoren** [comment]
From the logs it looks like there are almost no links found. That might be an issue with the mapping step, how many entries are in the bed file from the mapping?

**Comment by skoren** [comment]
Idle, no links mapped
