### ISSUE TITLE
Arima 2-enzymes restriction site (^GATC and G^ANTC)

### ISSUE THREAD

**Issue by edanchin** [marbl/SALSA#168]
Hi,
Not sure I have understood exactly how to indicate the restriction sites used with -e option.
In the README, it is written the following:
"You will need to specify the restriction site for the enzyme which was used for Hi-C experiment while running SALSA in -e option. "
In our experiments, we have used Arima 2-enzymes kit with one enzyme cutting before the G at ^GATC and the other one cutting between the G and A at G^ANTC.
While for the first enzyme it seems clear I should input -e GATC, for the second enzyme, what should I set?
If I input -e GANTC, the program will probably misunderstand and search for ^GANTC restriction sites instead of G^ANTC, right?
How to indicate that the restriction site is between G and ANTC ?
Many thanks for your support.

**Comment by skoren** [comment]
That's fine, the exact restriction site doesn't need to be specified, just the sequence context. The VGP uses the same restrictions sites (e.g. see https://s3.amazonaws.com/genomeark/index.html?prefix=species/Acanthisitta_chloris/bAcaChl4/genomic_data/arima/) and they are specified as `GATC, GANTC` to salsa.

**Comment by edanchin** [comment]
Dear Sergey,

Thanks a lot for the information, I will use SALSA on our Arima data with -e GATC,GANTC.

Best

Etienne


--
______________________________________________________
                                  Etienne G.J. Danchin
                                 http://edanchin.org
______________________________________________________
Institut Sophia Agrobiotech
INRAE - Univ. Côte d'Azur - CNRS
--
400 route des Chappes, BP 167
06903 Sophia-Antipolis Cedex
France
--
http://www.paca.inra.fr/institut-sophia-agrobiotech
Tel. +33 492 386 402
Fax. +33 492 386 587
________________________________
De : Sergey Koren ***@***.***>
Envoyé : mercredi 10 août 2022 19:31
À : marbl/SALSA
Cc : Etienne Danchin; Author
Objet : Re: [marbl/SALSA] Arima 2-enzymes restriction site (^GATC and G^ANTC) (Issue #168)


That's fine, the exact restriction site doesn't need to be specified, just the sequence context. The VGP uses the same restrictions sites (e.g. see https://s3.amazonaws.com/genomeark/index.html?prefix=species/Acanthisitta_chloris/bAcaChl4/genomic_data/arima/) and they are specified as GATC, GANTC to salsa.

-
