### ISSUE TITLE
Mate-pair in SALSA

### ISSUE THREAD

**Issue by aabaricalla** [marbl/SALSA#170]
Hi!

I was working with old genomic data produced by Illumina Mate pair sequencing.
This strategy cuts linear intrachromosomal regions in 3kb, 5kb, 8kb, or 20kb segments, ligate, circularizes the fragments, and then sequences the ligated part to recover the extremes of the fragments. [Image 1 from this paper shows this.](Pair_Sequencing_as_a_Powerful_Clinical_Tool_for_the_Characterization_of_Cancers_with_a_DNA_Viral_Etiology).

Could this data be compared to Hi-C data? 
This sequencing strategy could be used with SALSA to scaffold genome assemblies?. 
any suggestions to optimize the results? 
Thanks in advance!

**Comment by skoren** [comment]
No, I wouldn't try to use mate-pairs in salsa. They are a very different datatype and have their own idiosyncrasies that salsa won't handle correctly.
