### ISSUE TITLE
Representation of broken contigs in FINAL.agp file

### ISSUE THREAD

**Issue by woodoo46** [marbl/SALSA#176]
Hi there,

I found these two interesting two lines in our FANAL.agp file:

scaffold_12     1       17600183        1       W       ptg000016l_1    1       17600183        +
scaffold_25     1       11839887        1       W       ptg000016l_2    1       11839887        +

I supposed that ptg000016l was broken into two parts (the sum of scaffold_12 and scaffold_25 is equal to the original length), however, from this representation, both scaffold_12 and scaffold_25 are from the first part of ptg000016l?

Thanks.

George

**Comment by skoren** [comment]
The format is a little confusing here, the start/end give the coordinates in the split sequence (so it starts at coordinate 1 in ptg000016l_2). To find the original coordinates of ptg000016l_2 in ptg000016l you need to look at input_breaks file in the run.
