### ISSUE TITLE
AGP file has 500bp gaps labelled as "scaffold" with linkage asserted but "na" given for linkage evidence

### ISSUE THREAD

**Issue by dgs108** [marbl/SALSA#179]
SALSA2 scaffolded my assembly (5004 contigs) into 3100 scaffolds. The AGP file produced shows that I have ~1000 gaps each of 500bp which are labeled "scaffold" in column 7, with linkage asserted ("yes" in column 8), but "na" is given for linkage evidence in column 9. My understanding is that na cannot be used as evidence of linkage, and while na can be used in column 9 if linkage is not asserted, that would mean that something other than "scaffold" must be used in column 7.

Also, do the 500bp gaps relate to the 250bp x 2 Hi-C reads?

Any advice would be much appreciated!

**Comment by skoren** [comment]
See the pull request #181 which updates the AGP to match the v2.1 spec. The gaps are unknown size which was defaulted to as 500bp but by the spec they should be 100bp. Linkage is asserted, based on proximity ligation evidence (e.g. HiC).
