### ISSUE TITLE
Contig Headers with Colons

### ISSUE THREAD

**Issue by malonge** [marbl/SALSA#20]
Hi there,

I have a few contigs in my assembly whose header contains a colon. For example:

```transfrag_1:293290599-293291609```

This appears to be causing an error in the ```generate_scaffold_graph()``` function of ```layout_unitigs.py```.

I specifically get the following error

```
Traceback (most recent call last):
  File "... /SALSA/layout_unitigs.py", line 904, in <module>
    generate_scaffold_graph()
  File "... /SALSA/layout_unitigs.py", line 397, in generate_scaffold_graph
    if contig_length[c1] <= int(args.cutoff) or contig_length[c2] <= int(args.cutoff):
KeyError: 'transfrag_1'
```

From looking around it looks like there is some extra information encoded in the ```contig_links_scaled_sorted_iteration_1``` which relies on the addition of a colon to the fasta headers. Then, this causes problems starting at 389 of ```layout_unitigs.py```. 

I could mess around and get it to work but I figure the presence of colons in fasta headers is common enough that I would bring it to your attention.

Thanks

**Comment by skoren** [comment]
There is an explicit check for this now which will abort the run immediately if it encounters ':', the user will still have to rename the fasta themselves before re-trying.
