### ISSUE TITLE
Is the parament -u outdated?

### ISSUE THREAD

**Issue by sr-c** [marbl/SALSA#59]
Thank you for the convenient tool. 
Following the README.md, I tried to use unitigs from canu to assist scaffording. But the parement `-u` seems not to exist. 
> run_pipeline.py: error: unrecognized arguments: -u unitigs_tiling.bed

If so, how could I scafford from the unitigs in current version?

**Comment by machinegun** [comment]
-u parameter is obsolete in the run_pipeline.py. You could use that with stitch.py script, which stitches unitigs in a contig based on that bed file.

**Comment by sr-c** [comment]
Thank you for your repIy. It seems `-u` parameter had been moved to `sitches.py` as `-b, --bed`. Please modifiy the `README.md` adapting to current version.

According to the `README.md`, I got 108 Mb `scaffolds_FINAL.fasta` with 51 scaffolds. Then I tried to stitch the unitigs as shown below. But I got only 80 Mb `output_scaffolds.fasta` with 4 scaffolds. Some unitigs were discarded during the stitching.

Did I make a mistake in the pipeline to scaffolding from the unitigs?
```bash
python ~/software/SALSA/run_pipeline.py \
-a reference_sequences/unitigs.fasta \
-l reference_sequences/unitigs.fasta.fai \
-b alignment.bed -e GATC -o scaffolds -m yes -g unitigs_graph.gfa

python ~/software/SALSA/stitch.py \
-b unitigs_tiling.bed \
-c reference_sequences/contigs.fasta \
-u reference_sequences/unitigs.fasta \
-p scaffolds/scaffolds_iteration_4.p \
-o output_scaffolds.fasta
```
Output as follows.
```bash
==============================
['tig00000003:FOW', 'tig00000006:FOW']
['tig00000003:FOW', 'tig00000006:FOW']
=============================
==============================
['tig00000048:FOW', 'tig00000055:FOW', 'tig00000001:FOW', 'tig00000024:FOW']
['tig00000048:FOW', 'tig00000055:FOW', 'tig00000001:FOW', 'tig00000024:FOW']
=============================
==============================
['tig00000019:FOW', 'tig00000021:REV', 'tig00000026:REV', 'tig00000017:FOW', 'tig00000012:REV']
['tig00000019:FOW', 'tig00000021:REV', 'tig00000026:REV', 'tig00000017:FOW', 'tig00000012:REV']
=============================
==============================
['tig00000057:REV', 'tig00000008:FOW']
['tig00000057:REV', 'tig00000008:FOW']
=============================
```
