### ISSUE TITLE
How to use Falcon assembly gfa to assist scaffolding

### ISSUE THREAD

**Issue by baozg** [marbl/SALSA#67]
Hi, 

I use the SALSA to scaffold the assembly (Falcon-Unzip + purge_haplotig) , SALSA increase the contig N50 20M to scaffolds N50 30M，the species I assemblyed have 23 chromosomes. It stroped after 5 iteration, but when I look the heatmap from .hic file, I think it can continue with more scaffolding, the heatmap show some joins singal.
![image](https://user-images.githubusercontent.com/20680150/56543479-27e6f480-65a4-11e9-8b96-904bc47dccea.png)

Also, I want to know how to use gfa from Faclon to assist scaffolding. Since I use Falcon-Unzip (it filter some contigs) and purge_haplotig (it reassign some contigs), the contigs number of the assembly less than initial gfa file.

Here is the command I use ：
python run_pipeline.py -a ctg.fa -l ctg.fa.fai -e GATC -b ctg.bed -o ./ -m yes -p yes

**Comment by machinegun** [comment]
I am unsure about using GFA from falcon-unzip for SALSA as I haven't done it myself. 

How much Hi-C coverage do you have for this particular genome? Also, what's the genome size?

**Comment by baozg** [comment]
It's a 880M genome. The total reads fed into SALSA is 423M.

**Comment by machinegun** [comment]
closing this issue for now. Let us know if you . have any questions.
