### ISSUE TITLE
Diploid assembly

### ISSUE THREAD

**Issue by fmarletaz** [marbl/SALSA#71]
Hi - Thanks for developing such as great tool. I have a question: I am dealing with a highly heterozygous species for which CANU is keeping both haplotypes. I am hesitating between running salsa before (using the assembly graph) or after haploidising the genome. Would that be a problem to map HiC on a diploid assembly, I guess it would dilute the signal. Thanks for your advice.

**Comment by machinegun** [comment]
Hi,

I wound recommend binning contigs into haplotypes and then running SALSA2 individually on each haplotype by mapping all the Hi-C data to each haplotype. There are several ways you could bin contigs. One of it is using [purge_haplotigs](https://bitbucket.org/mroachawri/purge_haplotigs). We also encountered issues of heterozygosity while using HiC for scaffolding. In [this](https://www.biorxiv.org/content/biorxiv/early/2018/12/10/492777.full.pdf) manuscript, we described the way we separated contigs into haplotypes.
