### ISSUE TITLE
No improvement of assembly after quick finish

### ISSUE THREAD

**Issue by nadegeguiglielmoni** [marbl/SALSA#72]
Hello,

I have ran SALSA successfully in the past, but this time I encounter a problem : the program finishes after iteration 2 is over, and the assembly is almost not changed. Here is the log : 

`('/HOME/genom_to_scaffold/salsa_scaffolding/desmarestia_salsa.alignment.bed', 'salsa_without_exp_genome_size_2/alignment_iteration_1.bed')
('/HOME/genom_to_scaffold/salsa_scaffolding/desmarestia_salsa.alignment.bed', 'salsa_without_exp_genome_size_2/alignment_iteration_1.bed')

bedfile loaded
python /HOME/SALSA/RE_sites.py -a salsa_without_exp_genome_size_2/assembly.cleaned.fasta -e DpnII > salsa_without_exp_genome_size_2/re_counts_iteration_1

Starting Iteration 1
python /HOME/SALSA/make_links.py -b salsa_without_exp_genome_size_2/alignment_iteration_1.bed -d salsa_without_exp_genome_size_2 -i 1 -x abc
bedfile started
bedfile loaded
python /HOME/SALSA/fast_scaled_scores.py -d salsa_without_exp_genome_size_2 -i 1
sort -k 5 -gr salsa_without_exp_genome_size_2/contig_links_scaled_iteration_1 > salsa_without_exp_genome_size_2/contig_links_scaled_sorted_iteration_1
python /HOME/SALSA/layout_unitigs.py -x abc -l salsa_without_exp_genome_size_2/contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d salsa_without_exp_genome_size_2
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 12544 edges = 6272
Hi-C implied edges = 0
/HOME/SALSA/break_contigs -a salsa_without_exp_genome_size_2/alignment_iteration_2.bed -b salsa_without_exp_genome_size_2/breakpoints_iteration_2.txt -l salsa_without_exp_genome_size_2/scaffold_length_iteration_2 -i 2 -s 100   > salsa_without_exp_genome_size_2/misasm_iteration_2.report
python /HOME/SALSA/refactor_breaks.py -d salsa_without_exp_genome_size_2 -i 2

Starting Iteration 2
python /HOME/SALSA/make_links.py -b salsa_without_exp_genome_size_2/alignment_iteration_2.bed -d salsa_without_exp_genome_size_2 -i 2
bedfile started
bedfile loaded
Starting Iteration 2
python /HOME/SALSA/layout_unitigs.py -x abc -l salsa_without_exp_genome_size_2/contig_links_scaled_sorted_iteration_2 -c 1000 -i 2 -d salsa_without_exp_genome_size_2
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 12544 edges = 6272
Hi-C implied edges = 0
/HOME/SALSA/break_contigs -a salsa_without_exp_genome_size_2/alignment_iteration_3.bed -b salsa_without_exp_genome_size_2/breakpoints_iteration_3.txt -l salsa_without_exp_genome_size_2/scaffold_length_iteration_3 -i 3 -s 100  > salsa_without_exp_genome_size_2/misasm_iteration_3.report
python /HOME/SALSA/refactor_breaks.py -d salsa_without_exp_genome_size_2 -i 3 > salsa_without_exp_genome_size_2/misasm_3.log`

Is it because the Hi-C information is exhausted? Is there any way to improve the scaffolding?

**Comment by machinegun** [comment]
Hi,

I see  `-e DpnII` option being used in the log. SALSA2 requires the binding site for the enzyme as an input, not the enzyme name itself. Did you try using `-e GATC` while running it?

**Comment by nadegeguiglielmoni** [comment]
Since I posted the issue, I reran the mapping + SALSA and it did several iterations this time. I guess the wrong format for the enzyme input must be the culprit, I must have gotten confused. I think it would still be better to have SALSA raise an error in this kind of case...

**Comment by machinegun** [comment]
Good suggestion! I'll add the error reporting in such case. Thanks.

**Comment by skoren** [comment]
Check for improper enzymes added
