### ISSUE TITLE
SALSA finishing but not producing scaffold_FINAL.fasta

### ISSUE THREAD

**Issue by KevinBredemeyer** [marbl/SALSA#75]
Hello,

I've seen similar issue reported previously but they all involve changing -e input from enzyme name to cut sequence and I am using -e DNASE.
I get the same issue as mentioned previously: SALSA runs and appears to finish without error, except no scaffold_FINAL.fasta is output. 
Terminal output: 
[salsa-troubleshoot.txt](https://github.com/machinegun/SALSA/files/3315114/salsa-troubleshoot.txt)
Commands Log:
[commands.log.txt](https://github.com/machinegun/SALSA/files/3315127/commands.log.txt)

Thanks!
Kevin

**Comment by KevinBredemeyer** [comment]
Any progress on this or am I missing something trivial?
Thanks,
Kevin

**Comment by machinegun** [comment]
Hi,

Do you mind sharing your data? I can try running it at my end to see what's up with it.

**Comment by machinegun** [comment]
Hi Kevin,

We have resolved the issue. Please use the latest commit to see if it works for you.

**Comment by ardy20** [comment]
I have also this issue. No scaffold_final is produced. I used Omni-C with -e DNASE option.

**Comment by gubrins** [comment]
I am also having the same issue, any solutions??
