### ISSUE TITLE
Converting to hic files costs too much time...

### ISSUE THREAD

**Issue by TypicalSEE** [marbl/SALSA#77]
Hi, I am using SALSA pipeline to assembly a plant genome. The pipeline finished successfully, but I encountered a problem while running the extra step which converts SALSA results to .hic files: this step has been running for too long and does not want to finish. It has been running for 12 days(32x CPU) on the cluster, and the output hic file is 480MB for now. I don't know whether it will finish at last... The draft genome size is about 1.7Gb. The command is as follow:

`sh USER/yujin/software/SALSA/convert.sh TT_scaffolds`

The STDOUT is like this:

### Step 7: convert to hic files
Not including fragment map
Start preprocess
Writing header
Writing body
...................................................................................................(endless dots)

I also tried using my desktop PC to run this step. The java process consumes all the 8 CPUs(Intel Core i7 4790 @3.6 GHz) and had been running for 14 days without finishing in the end. I had to kill it at last. So is it because the genome size is too big or some other reason I can't imagine?  I would appreciate it very much if you could help me!

**Comment by machinegun** [comment]
Hi,

The genome size is not very big and it shouldn't take that long.  Can you try rerunning with more jvm memory? In line 18 of convert.sh, use option -Xmx30g. .

**Comment by TypicalSEE** [comment]
Thanks for your reply. I modified the convert.sh script as you said and reran it with 16 CPU. The memory consumption is "vmem=1015.707M, maxvmem=2.488G". It's been running for 96 hours and still hasn't finished. Do you have any other suggestions?

**Comment by machinegun** [comment]
I am not sure. I would recommend you to contact juicer authors for investigating this. Let us know if you have any other questions.

**Comment by theshowmustgolangon** [comment]
@ghuryejay @TypicalSEE Experiencing the same problem. Are there any suggestions you found?

**Comment by yuzhenpeng** [comment]
The same problem. Are there any suggestions you found?
