### ISSUE TITLE
Assembly correction using Juicebox; needs .assembly file.

### ISSUE THREAD

**Issue by harish0201** [marbl/SALSA#80]
Hi!

I'm curating the SALSA scaffolded genome using JuiceBox andI have generated the .hic file as needed on the final scaffolds.

However, (I might be wrong here) we also need a .assembly file similar to something obtained from here: https://www.dropbox.com/s/13cppe80692oee9/demo.zip?dl=0

Currently we have the agp for the final scaffolds. I would really appreciate it if you could create the .assembly file as well!

**Comment by machinegun** [comment]
Hi,
We currently don't generate .assembly file as an output of SALSA. We will provide support for .assembly file in future.
