### ISSUE TITLE
Unexpected stop at iteration 2 - again

### ISSUE THREAD

**Issue by michaelbroe** [marbl/SALSA#81]
Like others before me, I am experiencing an unexpected stop at iteration 2, but I don't think I am making the mistakes that were previously reported. I am running this on a machine with 64 CPU and 256 GB memory. 

Here is my command line:

 `python ~/local/src/SALSA/run_pipeline.py -a genome.scf.fasta -l genome.scf.fasta.fai -b alignment-Hi-C.bed -e AAGCTT -o SALSA-out`

Here is the commands.log:
`/home/broe.1/local/src/SALSA/break_contigs_start -a SALSA-out/alignment_iteration_1.bed -l SALSA-out/scaffold_length_iteration_1 > SALSA-out/input_breaks -s 100python /home/broe.1/local/src/SALSA/correct.py  genome.scf.fasta SALSA-out/input_breaks SALSA-out/alignment_iteration_1.bed SALSA-outpython /home/broe.1/local/src/SALSA/RE_sites.py -a SALSA-out/assembly.cleaned.fasta -e AAGCTT > SALSA-out/re_counts_iteration_1
python /home/broe.1/local/src/SALSA/make_links.py -b SALSA-out/alignment_iteration_1.bed -d SALSA-out -i 1 -x abc
python /home/broe.1/local/src/SALSA/fast_scaled_scores.py -d SALSA-out -i 1
sort -k 5 -gr SALSA-out/contig_links_scaled_iteration_1 > SALSA-out/contig_links_scaled_sorted_iteration_1
python /home/broe.1/local/src/SALSA/layout_unitigs.py -x abc -l SALSA-out/contig_links_scaled_sorted_iteration_1 -c 1000 -i 1 -d SALSA-out
/home/broe.1/local/src/SALSA/break_contigs -a SALSA-out/alignment_iteration_2.bed -b SALSA-out/breakpoints_iteration_2.txt -l SALSA-out/scaffold_length_iteration_2 -i 2 -s 100   > SALSA-out/misasm_iteration_2.report
python /home/broe.1/local/src/SALSA/refactor_breaks.py -d SALSA-out -i 2
python /home/broe.1/local/src/SALSA/make_links.py -b SALSA-out/alignment_iteration_2.bed -d SALSA-out -i 2
python /home/broe.1/local/src/SALSA/fast_scaled_scores.py -d SALSA-out -i 2
sort -k 5 -gr SALSA-out/contig_links_scaled_iteration_2 > SALSA-out/contig_links_scaled_sorted_iteration_2`

And here are the contents of my SALSA-out directory:

`alignment_iteration_1.bed
alignment_iteration_2.bed
assembly.cleaned.fasta
breakpoints_iteration_2.txt
commands.log
contig_links_iteration_1
contig_links_iteration_2
contig_links_scaled_iteration_1
contig_links_scaled_iteration_2
contig_links_scaled_sorted_iteration_1
contig_links_scaled_sorted_iteration_2
input_breaks
links_avoid_iteration_2
misasm_2.DONE
misasm_iteration_2.report
re_counts_iteration_1
re_counts_iteration_2
scaffold_length_iteration_1
scaffold_length_iteration_2
scaffolds_iteration_1.p`

Let me know if you need more info. Thanks in advance for any help.

Cheers,
Michael

**Comment by machinegun** [comment]
Hi,

Looks like your scaffolding didn't run all the way till the end as there's no scaffolds_FINAL.fasta file. Do you mind sharing the data with us so that we can try debugging it better?

**Comment by michaelbroe** [comment]
That's fine. The assembly is 1.6G and the .bed file is 2.7G. What's the best way to get them to you?

**Comment by michaelbroe** [comment]
Any update on this?

**Comment by michaelbroe** [comment]
Hi again, can you confirm you received the data?

**Comment by skoren** [comment]
Yes, the data transferred OK but have not yet run it.

**Comment by michaelbroe** [comment]
Great, thanks for the confirmation.

**Comment by machinegun** [comment]
Hi,
There was a function in the code that was exiting if there are no HiC links without printing the final scaffolds. We have fixed this and you can use the latest commit to reach to final fasta file. Please let us know if you run into any other issues.

**Comment by skoren** [comment]
The general issue was that you have very low HiC coverage and low count links in the input. Salsa will warn you now about the low coverage rather than terminating but I wouldn't expect much scaffolding to happen here.
