### ISSUE TITLE
low coverage settings

### ISSUE THREAD

**Issue by MichelMoser** [marbl/SALSA#83]
Not really an issue but rather a question about setting parameters: 

I have a dataset of about 2 mio Hi-C reads from a Miseq test-run and was wondering if there are parameters to adjust for low coverage of Hi-C contact points in SALSA. 

We have a decent assembly of 2000 contigs and I assume the Hi-C data provides enough information to link those together into larger scaffolds. 

When i run SALSA by default, it manages to scaffold only a few contigs. 
Any hints would be appreciated. 

Thank you, 
Michel 

PS: running it with genome graph included

**Comment by machinegun** [comment]
Hi,

What's the sequencing and physical coverage of your HiC data?
