### ISSUE TITLE
gfa after assembly correction

### ISSUE THREAD

**Issue by edotau** [marbl/SALSA#86]
if we correct/polish our contigs/unitigs that come out of canu with other sequencing methods, can we still use the same GFA files that originally came out of canu? or do we have to generate those file formats another method if we want to input them into SALSA with Hic?

**Comment by skoren** [comment]
The same gfa should still be OK to use, it will provide valid link information though the CIGAR strings (which aren't used by SALSA) won't be accurate anymore
