### ISSUE TITLE
Not enough Hi-C reads for scaffolding

### ISSUE THREAD

**Issue by bgbrink** [marbl/SALSA#87]
When I run SALSA, I get the following messages:

```
bedfile loaded
Starting Iteration 1
bedfile started
bedfile loaded
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 266 edges = 185
Hi-C implied edges = 0
Starting Iteration 2
bedfile started
bedfile loaded
Starting Iteration 2
WARNING: Not enough Hi-C reads for scaffolding
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 92 edges = 53
Hi-C implied edges = 0
Starting Iteration 3
bedfile started
bedfile loaded
Starting Iteration 3
WARNING: Not enough Hi-C reads for scaffolding
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 226 edges = 113
Hi-C implied edges = 0
```
Our HiC data is quite deep, I get a 7.3GB bam file for each read pair. I followed the Arima Genomics pipeline linked in the Readme to preprocess the reads, this is the head of the sorted bed file that is the input to SALSA (the size of the bed file is 6.1GB):

```
000000F_0	2651629	2651705	NB500937:320:HGKNFAFXY:1:11101:10000:10373/1	60	-
000000F_0	3368380	3368427	NB500937:320:HGKNFAFXY:1:11101:10000:10373/2	60	+
000000F_0	280823	280899	NB500937:320:HGKNFAFXY:1:11101:10000:14278/1	60	-
000009F_0	361371	361447	NB500937:320:HGKNFAFXY:1:11101:10000:14278/2	60	+
000003F_0	1463548	1463606	NB500937:320:HGKNFAFXY:1:11101:10000:1502/1	60	-
000003F_0	1600628	1600702	NB500937:320:HGKNFAFXY:1:11101:10000:1502/2	60	+
000003F_0	290132	290208	NB500937:320:HGKNFAFXY:1:11101:10000:17747/1	60	-
000021F_0	87027	87102	NB500937:320:HGKNFAFXY:1:11101:10000:17747/2	60	+
000008F_0	449604	449680	NB500937:320:HGKNFAFXY:1:11101:10000:18735/1	60	-
000008F_0	449457	449533	NB500937:320:HGKNFAFXY:1:11101:10000:18735/2	60	+

```

Is there anything wrong with the formatting? I think I can rule out that we did not sequence deep enough.

**Comment by skoren** [comment]
I think the warning is being printed too frequently, even if there are good weight links in the data. There aren't very many nodes in your graph (I'd guess your assembly is pretty continuous). The formatting of the file looks OK. Can you check for files named ```contig_links_scaled_iteration_*``` in your output, are there edges there that have weight > 1? If so I think it is scaffolding, just outputting the warning incorrectly.
