### ISSUE TITLE
make error: cc1plus error unrecognized command

### ISSUE THREAD

**Issue by hungweichen0327** [marbl/SALSA#89]
Dear community:

I use following script for installation.
```
git clone https://github.com/machinegun/SALSA.git

conda create -n SALSA python=2.7
source activate SALSA
conda install boost networkx==1.11
```
When I type
```
cd SALSA
make
```
I got the error:
```
g++ -O3 -Wall -Wextra -std=c++11 -o break_contigs break_contigs.cpp
cc1plus error unrecognized command line option -std=c++11
make: *** [break_contigs] Error 1
```

How do I solve this problem?
Thank you!

**Comment by skoren** [comment]
What operating system are you on and what does g++ --version report?

**Comment by hungweichen0327** [comment]
Dear Dr. Sergey,

I am running on server. below is the output when I type ``uname-a``
```
Linux h71 2.6.32-431.11.2.el6.x86_64 #1 SMP Tue Mar 25 19:59:55 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
And below is the output when I type ``g++ --version``
```
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
Copyright (C) 2010 Free Software Foundation, Inc.
```

**Comment by skoren** [comment]
You're using a very old GCC that doesn't support C++11. You could try editing the make file to use -std=c++0x from -std=c++11 which might work. However, it would be better to update to at least GCC 4.7.

**Comment by hungweichen0327** [comment]
Thank you for the explanation. Sorry, I am a beginner of using conda. I don't know how to update gcc version in SALSA environment of conda.

**Comment by hungweichen0327** [comment]
``
