### ISSUE TITLE
Question about the format of alignment.bed

### ISSUE THREAD

**Issue by xuzhougeng** [marbl/SALSA#91]
I use another program to get the alignment.bam insteads of <https://github.com/ArimaGenomics>

And I use the `bamToBed` and `sort` to extract the alignment.bed from the bam file. 

I found the some of the fastq is not paired, as you can see in the following

```
1. tig00011491     8044955 8045105 A00153:502:HTLJFDSXX:3:1101:10077:20697/1
2. tig00011491     8045120 8045270 A00153:502:HTLJFDSXX:3:1101:10077:20697/2
3. tig00011525     7628353 7628503 A00153:502:HTLJFDSXX:3:1101:10095:9831/1
4. tig00011528     1899597 1899745 A00153:502:HTLJFDSXX:3:1101:10104:17519/1
5. tig00000156     2576824 2576974 A00153:502:HTLJFDSXX:3:1101:10140:3396/2
6. tig00011549     3652048 3652198 A00153:502:HTLJFDSXX:3:1101:10267:1485/1
7. tig00011549     3666040 3666190 A00153:502:HTLJFDSXX:3:1101:10267:1485/2
```

Can I use this file as the input of SALSA, or should I remove the unpaired fastq and make sure each fastq is paired?

Thanks !

**Comment by ghuryejay** [comment]
You can use the bed file without removing unpaired reads.  You just need it
sorted by read names.

**Comment by xuzhougeng** [comment]
@ghuryejay Thanks for your kindly help
