### ISSUE TITLE
mis-assembly detection option

### ISSUE THREAD

**Issue by xuzhougeng** [marbl/SALSA#92]
Dear developers

After I run the SALSA with `-m yes`, I find some obvious error of the assembly is not correct by SALSA, so I read all related issues and I found #34 . The developer replied that "an option to support mate pairs upto certain separation to be used for misassembly correction." 

And I find the the option `-f FILTER Filter bed file for contigs present in the assembly`,  but I do not know how to use it. Could you descript it more detailly? 

What options can  I tune for error correction?

Thanks!

**Comment by skoren** [comment]
The -f option isn't going to be useful for mis-assembly detection, that's mean for use when you have gfa and unitig outputs to scaffold.

The issue in #34 was addressed in later salsa versions which limit the maximum distance for supporting mates. If you're using Salsa 2.2, these changes should already be the default. The default is to only consider links 10 times shorter than the contig length, which is not exposed as a user option. You could experiment by changing this in the code and seeing how it affects the breaking. I'd also suggest looking at the HiC coverages from the bed files as in #34 around your putative mis-assembly to see what the coverage actually looks like there.
