### ISSUE TITLE
Does SALSA apply a mapping quality (MAPQ) filter?

### ISSUE THREAD

**Issue by melop** [marbl/SALSA#94]
Hello, does SALSA apply any mapping quality (MAPQ) filter? Due to the repetitiveness of our genome, only around 60% of reads are mappable (even using normal Truseq libraries) at MAPQ>30. What would be the recommendation in this case?

Thank you!

**Comment by ghuryejay** [comment]
If you use Arima mapping pipeline, it would filter all the reads with mapq less than 30 and remove them from further analysis.

**Comment by ArimaAnthony** [comment]
The Arima mapping pipeline's default MAPQ filter is 10, but you can increase it in the configuration section to 30. See the parameter called "MAPQ_FILTER".
