### ISSUE TITLE
what should i put for scaffolds_iteration_3.p in stitch.py

### ISSUE THREAD

**Issue by anjiyuan** [marbl/SALSA#95]
i tried to stitch unitigs.fasta file using 
>python2 stitch.py -c xxx.contigs.fasta -u xxx.unitigs.fasta -p scaffolds_iteration_3.p -o output_scaffold_stitched_3p.fasta
I got error:
==============================================
Traceback (most recent call last):
  File "/home/an/bin/SALSA/SALSA-master/stitch.py", line 29, in <module>
    scaffolds = pickle.load(open(args.pickle,'r'))
IOError: [Errno 2] No such file or directory: 'scaffolds_iteration_3.p'
=============================================
if i create an empty file scaffolds_iteration_3.p, i still got error EOFError.

thanks
anji

**Comment by skoren** [comment]
Did your code run for 3 iterations? The 3.p is just an example in the readme. What is the content of your folder where you ran salsa?
