### ISSUE TITLE
No change in scaffold_FINAL

### ISSUE THREAD

**Issue by sstwins21** [marbl/SALSA#96]
Hi,

I have used SALSA to anchor my assembly using Hi-c reads. I have filtered my bam file using matlock and converted to bed as an input.

But, when I checked the quast after SALSA, there seems to be no change at all...
This is the command line I used to run SALSA:

python run_pipeline.py -a 1i_polar_flye_racon.fasta -l 1i_polar_flye_racon.fasta.fai -b sorted_mathlock_polar_flye.bed -e GATC -o salsa -m yes -p yes

Is there something wrong with my command line?
Why wouldn't Hi-c reads connects my scaffolds?

Kind regards,
Shane

**Comment by ghuryejay** [comment]
Hi Shane,

What's the coverage of  the HiC data you're working with?
